- balances/cli.go
- cmd/monitorism/cli.go
- withdrawals/cli.go
- withdrawals/monitor.go
Help Text:
```
NAME:
Monitorism withdrawals - Monitors proven withdrawals on L1 against L2
USAGE:
Monitorism withdrawals [command options] [arguments...]
DESCRIPTION:
Monitors proven withdrawals on L1 against L2
OPTIONS:
--l1.node.url value             Node URL of L1 peer (default: "127.0.0.1:8545") [$MONITORISM_L1_NODE_URL]
--l2.node.url value             Node URL of L2 peer (default: "127.0.0.1:9545") [$MONITORISM_L2_NODE_URL]
--event.block.range value       Max block range when scanning for events (default: 1000) [$MONITORISM_EVENT_BLOCK_RANGE]
--loop.interval.msec value      Loop interval of the monitor in milliseconds (default: 60000) [$MONITORISM_LOOP_INTERVAL_MSEC]
--start.block.height value      Starting height to scan for events (default: 0) [$MONITORISM_LOOP_INTERVAL_MSEC] …
```
> feat(wd-mon)

- cmd/monitorism/cli.go
- fault/cli.go
- fault/monitor.go
- withdrawals/monitor.go
help text options
```
--l1.node.url value             Node URL of L1 peer (default: "127.0.0.1:8545") [$MONITORISM_L1_NODE_URL]
--l2.node.url value             Node URL of L2 peer (default: "127.0.0.1:9545") [$MONITORISM_L2_NODE_URL]
--loop.interval.msec value      Loop interval of the monitor in milliseconds (default: 60000) [$MONITORISM_LOOP_INTERVAL_MSEC]
--start.output.index value      Output index to start from. -1 to find first unfinalized index (default: -1) [$MONITORISM_START_OUTPUT_INDEX]
--optimismportal.address value  Address of the OptimismPortal contract [$MONITORISM_OPTIMISM_PORTAL]
```
Sample output
```
hamdiallam@hamdioplabsmbp monitorism % go run ./cmd/monitorism fault --start.output.index -1 --l1.node.url https://rpc.ankr.com/eth --l2.node.url https://mainnet.optimism.io …
```
> feat(fault-mon)

- balances/cli.go
- balances/monitor.go
- cmd/monitorism/cli.go
- fault/monitor.go
- multisig/cli.go
- multisig/monitor.go
- withdrawals/monitor.go
helptext. `OP_SERVICE_ACCOUNT_TOKEN` must be set outside the process
```
--l1.node.url value             Node URL of L1 peer (default: "127.0.0.1:8545") [$MULTISIG_MON_L1_NODE_URL]
--optimismportal.address value  Address of the OptimismPortal contract [$MULTISIG_MON_OPTIMISM_PORTAL]
--safe.address value            Address of the Safe contract [$MULTISIG_MON_SAFE]
--op.vault value                1Pass Vault name [$MULTISIG_MON_1PASS_VAULT_NAME]
```
Sample Output (with a sample vault on my computer):
```
hamdiallam@hamdioplabsmbp monitorism % go run ./cmd/monitorism multisig --l1.node.url https://rpc.ankr.com/eth --optimismportal.address 0xbEb5Fc579115071764c7423A4f12eDde41f106Ed --safe.address 0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A --loop.interval.msec 1_000 --op.vault Hypatia …
```
> feat(multisig.mon)

- .circleci/config.yml
- .github/CODEOWNERS
A clear and concise description of the features you're adding in this pull request.
**Tests**
Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> adding context for circleci

- op-monitorism/global_events/monitor.go
- op-monitorism/global_events/monitor_test.go
Fix the incorrect filtering by ensuring only the addresses specifed into the yaml is listenning at.
Also add a test to ensure the formatHash is working with more complexe event topics.
**Tests**
Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.
> Fix: Incorrect Filtering Listen to wide the events.

- op-monitorism/global_events/monitor.go
Fix a bug sending the wrong function name into the grafana metrics.
This was cause because the metrics sent was hardcoded on the `[0]` which can cause an issue when the rules has more than one event monitored.
> patch: fix bug sending the wrong function name into the grafana metrics.

- README.md
- op-monitorism/cmd/monitorism/cli.go
- op-monitorism/secrets/bindings/checksecrets.go
- op-monitorism/secrets/bindings/drippie.go
- op-monitorism/secrets/cli.go
- op-monitorism/secrets/monitor.go
Introduces a new monitoring package that keeps track of CheckSecrets contracts used by a particular Drippie contract. Queries the Drippie contract for new drips and stores those drips for later. Iterates over stored drips during each loop to determine if the provided secrets are revealed or not.
> feat: introduce monitoring for CheckSecrets

- op-monitorism/global_events/monitor.go
- op-monitorism/global_events/types.go
Fix the metrics and also refactor the log at the start of the service. 
Fix a panic from cardinality issue: 
```bash
panic: inconsistent label cardinality: expected 8 label values but got 7 in []string{"lskjdflskjdflskjfsdjkf", "Template SafeExecution Events (Success/Failure) L1 ETHEREUM", "P5", "ExecutionSuccess(bytes32,uint256)", "0x19c50EFcbFBd2b704f14F6c2Bd0B0E508635Dbe0", "20127231", "0x33cf84d899482baaf994483558c9d14d7768f1e24af4edd9ce29c313d294c3c8"}
goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*CounterVec).WithLabelValues(...)
/Users/ethnical/go/pkg/mod/github.com/prometheus/client_golang@v1.19.0/prometheus/counter.go:284
github.com/ethereum-optimism/monitorism/op-monitorism/global_events.(*Monitor).checkEvents(0x1400015ce00, {0x2?, 0x2?}) …
```
> Fix the previous metrics by using a counter into `global_event`. 

- op-monitorism/global_events/monitor.go
…avoid unique metrics!
Remove the metrics the unique metrics to help against cardinality issue + alerting. 
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> fix: Fix the metrics to remove the `Txhash` and the `blocknumber`

- op-monitorism/global_events/monitor.go
There is some case that when the testing (monitoring all the addresses) or in the future the address is not making a metrics unique. 
Our decision was to remove the address to make metrics unique.
> chore: remove the address to make metrics unique

- README.md
- op-monitorism/balances/README.md
- op-monitorism/cmd/monitorism/cli.go
- op-monitorism/drippie/README.md
- op-monitorism/fault/README.md
- op-monitorism/liveness_expiration/README.md
- op-monitorism/liveness_expiration/bindings/GnosisSafe.go
- op-monitorism/liveness_expiration/bindings/LivenessGuard.go
- op-monitorism/liveness_expiration/bindings/LivenessModul.go
- op-monitorism/liveness_expiration/cli.go
- op-monitorism/liveness_expiration/monitor.go
- op-monitorism/multisig/README.md
- op-monitorism/secrets/README.md
Liveness expiration module is a monitoring dedicated for the safes.
Ensuring that owners that operates the safes are still actives enough.
To do so we are monitoring multiples metrics like: 
- `blockTimestamp`: The block Timestamp of the latest block number on L1.
- `highestBlockNumber`: The lastest block number height on L1.
- `lastLiveOfAOwner`: Get the last activities for a given safe owner on L1.  
- `intervalLiveness`: the *interval* (in seconds) from the `LivenessModule` on L1.  
The alerts logic will be written into prometheus, thanks to the metrics we have right now.
> Adding new monitor (Safe Liveness Expiration)

- op-monitorism/withdrawals/cli.go
removing condition for LoopIntervalMsec that causes issues
**Tests**
tested locally.
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
> removing condition for LoopIntervalMsec that causes issues

- .gitignore
- op-defender/cmd/defender/cli.go
- op-defender/psp_executor/README.md
- op-defender/psp_executor/api_test.go
- op-defender/psp_executor/cli.go
- op-defender/psp_executor/defender.go
A PR to execute a hard-coded transaction (sent 1wei to  `0x4141414142424242414141414242424241414141` with data=`0x414243`) on forked L1 on Sepolia using a well known privatekey.
From a simple cURL will trigger the onchain execution. 
We can see that the [transaction on tenderly](https://dashboard.tenderly.co/explorer/fork/82c36ace-0b2f-40a5-82d1-25e085a5d82b/simulation/eda7acc6-b598-4cbf-8035-8c42e0064a79) is a simple movemement of 1 wei to `0x4141414142424242414141414242424241414141` with calldata=`0x414243`.
**Tests**
I made some tests using the HTTP API directly using: 
```bash
curl -X POST http://localhost:8080/api/psp_execution \-H "Content-Type: application/json" \-d '{"pause": true, "timestamp": 1719432011, "operator": "Tom"}'
```
To make better testing, I had to …
> Add a onchain execution on forked network with Hardcoded values.

- op-defender/psp_executor/api_test.go
- op-defender/psp_executor/defender.go
This PR allows to fetch the private-key from the env directly and remove the hardcoded dummy privatekey from the codebase.
This will make sure that the private key fetch is with the correct format.
Using the environnement variable `PSPEXECUTOR_MON_PRIVATE_KEY` like below:  
```shell
export PSPEXECUTOR_MON_PRIVATE_KEY=2a871[....]3dff6d409c # removed the `0x` for better clarity but this one can be kept. 
```
I also increase the robustness of the HTTP method `/api/psp_execution` to make sure only the exact amount of args are strictly necessary also added a protection again to large payload size (> 1MB) that was missing (added some tests accordingly).  
**Tests** 
I have refactor and added some tests like: 
- `TestCheckAndReturnPrivateKey()`: tests the …
>  Fetching PrivateKey from Environnement and Execute onchain transaction.

- .gitignore
- op-defender/psp_executor/api_test.go
- op-defender/psp_executor/defender.go
This is small PR to refactor the function `checkPauseStatus()` to add a better logging + better name convention.
This also include a new GET HTTP method for the healthcheck at path `/api/healthcheck` to ensure the service is up. 
I added tests accordingly and also modified the previous tests. 
For the logging added a small recap of information directly at the booting to make sure all the params are correct: 
**Tests**
```bash
$go test -v
PASS
ok      github.com/ethereum-optimism/monitorism/op-defender/psp_executor        0.627s
```
> Refactoring + improve logging and add a Get method `api/healthcheck`

- op-defender/psp_executor/api_test.go
- op-defender/psp_executor/cli.go
- op-defender/psp_executor/defender.go
In this PR, I have added a new required arg. 
We can use it from environnement with`PSPEXECUTOR_MON_SUPERCHAINCONFIG_ADDRESS` or  from the cli: `--superchainconfig.address`. 
To use it, we can do: 
```shell
export PSPEXECUTOR_MON_SUPERCHAINCONFIG_ADDRESS=0xC2Be75506d5724086DEB7245bd260Cc9753911Be 
```
I have also updated the tests accordingly and make sure the values will be printed at the start of the service.  
**Tests**
I have run the tests and modified to test to ensure this is taking in consideration this arguments.
> feat: Add superchainconfig fetched from env variables. 

- .circleci/config.yml
This PR add the _go test_ into the CI to ensure that tests are correct each time when we are pushing into a PR into `op-defender` project. 
The CI test is named: `op-defender-golang-test`. 
**Tests**
This intervene into the https://github.com/ethereum-optimism/security-pod/issues/142. 
I did only `op-defender` for now, and will do `op-monitorism` once the tests are fixed again.
> Add go test for `op-defender` into directly into the CI.  

- .circleci/config.yml
- op-monitorism/global_events/types_test.go
This PR fix the the previous tests that changed into `op-monitorism` and add a `newlogger`. 
Also this include the CI tests that show that the current tests are passing.
closes https://github.com/ethereum-optimism/security-pod/issues/142
> Fix test + add testing into the CI for `op-monitorism`. 

- op-defender/psp_executor/api_test.go
- op-defender/psp_executor/defender.go
This PR Improve the HTTP server response + type usage `common.hash` instead of `String`.  This now return the `TxHash` to help the triagger to quickly make sure the transaction is valid on chain. 
This also introduce an error if the super-chain is not pause after the transaction has been executed without any error.
And also return an error if the superchain is paused before doing the pause. 
**Tests**
Fix the tests with the new signatures. 
This is part of the https://github.com/ethereum-optimism/security-pod/issues/148
> Improve the HTTP server response + type usage `common.hash` instead of `String`. 

- op-defender/psp_executor/api_test.go
- op-defender/psp_executor/defender.go
This PR addresses an issue with parsing the PSPs json file and improves the tests for better coverage.
**Tests**
The following functions are now covered with tests:
- `AddressFromPrivateKey`
- `CheckPauseStatus`
- `SendTransaction`
Other tests were improved to cover all possible cases and sometimes fix incorrect input for the tests.
The coverage of the op-defender project can be found below:
[psp_executor_ Go Coverage Report.pdf](https://github.com/user-attachments/files/17033623/psp_executor_.Go.Coverage.Report.pdf)
> Improve testing

- .circleci/config.yml
- Makefile
As discussed privately with @Ethnical, this is a contribution to the PR #62 for the issue #69. `golangci-lint` does not support monorepos, so it was necessary to change the directory to the appropriate project before running the linter. The `Makefile` has been updated to reflect this change.
Then the `circleci` file was updated to use the appropriate target in the `Makefile`, utilizing the `project_name` variable.
An attempt was made to fix the `restore_cache` action, but as I wasn't able to fully test it, there may still be issues.
The new target in `Makefile` returns the following output:
_op-monitorism-lint-go_
_op-defender-lint-go_
**Metadata**
- Fixes #69
> Fix go-lint in CI

- op-defender/psp_executor/README.md
- op-defender/psp_executor/api_test.go
- op-defender/psp_executor/cli.go
- op-defender/psp_executor/defender.go
- op-defender/psp_executor/simulator.go
This PR introduce a simulator for testing the validity of the PSPs and send the metrics of the simulation through prometheus. 
If the simulation of the transaction is not valid. Then, we will not execute the Onchain transaction like below:  
When the simulation succeed this will continue the workflow and pause the superchain config: 
On the following small video we can see differents cases that the PSPs might be valid, or invalid, or not present with the correct nonces. 
We can see that the PSPs are simulated every 2 seconds approx and if there is incorrect data then this will return a value and metrics into prometheus.
https://github.com/user-attachments/assets/65c57c74-add2-4575-85a9-b4b2da80d826
**Tests**
Please describe any tests you've added. If you've added no tests, …
> WIP: Feat(Simulation) to `SimulateTransaction()` the PSPs before executing them onchain

- op-monitorism/global_events/README.md
Fixed some typos and clarified that an option requires a directory and not a file in the Readme.md of Global Events.
**Tests**
N/A. Change to doc.
**Metadata**
N/A
> Clatifications to the Global Event README.md

- .circleci/config.yml
- Makefile
- op-defender/Makefile
- op-defender/psp_executor/api_test.go
- op-defender/psp_executor/defender.go
- op-defender/psp_executor/simulator.go
- op-monitorism/fault/monitor.go
- op-monitorism/global_events/monitor.go
- op-monitorism/global_events/monitor_test.go
- op-monitorism/global_events/types.go
- op-monitorism/global_events/types_test.go
- op-monitorism/liveness_expiration/monitor.go
- op-monitorism/multisig/monitor.go
- op-monitorism/secrets/monitor.go
- op-monitorism/withdrawals/monitor.go
This PR is adding the `go-linter` into the CI. 
This will allow us to improve the code clarity each time we are pushing. 
Before pushing the new linting we decided to clean the linting issues to avoid having the CI failing thanks @nodauf for his contribution here.
**Tests**
All tests have been down locally + into the current CI. 
**Metadata**
Fixes https://github.com/ethereum-optimism/monitorism/issues/69
> Add `go-linter` to the CI + Fix the previous Linting issues

- op-defender/psp_executor/utils.go
This PR improve the return of the function `weiToEther()` when the input is zero this will return 0.
> chore: return zero if the value is 0 for `weiToEther`

- .circleci/config.yml
Building for arm64 on release of the images.
**Tests**
Add support for arm64 on release of docker.
**Metadata**
This will fix the issue 170: https://github.com/ethereum-optimism/security-pod/issues/170
> Add `ARM64` architecture Docker images

- .circleci/config.yml
Updates our go tests to use the ci runner so that we can run tests that rely on anvil and other forge utilities.
> feat: use ci runner for go tests

- op-monitorism/transaction_monitor/README.md
The typo is in this sentence:
> "A `start_block` set to `0` indicates latest block."
Correction: 
> "A `start_block` set to `0` indicates the latest block."
Fixed.
> docs: typo fix Update README.md

- op-defender/psp_executor/README.md
- op-monitorism/multisig/monitor.go
1. File: op-monitorism/multisig/monitor.go
- "number of unexpcted rpc errors"
+ "number of unexpected rpc errors"
Reason: Missing letter 'e' in word "unexpected"
2. File: op-defender/psp_executor/README.md
- `/api/healtcheck`
+ `/api/healthcheck`
>  Fix typos in documentation and code

- op-monitorism/Dockerfile
Doing some testing with @jelias2 and we discovered that in order for monitorism to be able to connect within the cluster, it needs ca-certificates installed on the image
**Tests**
No tests added, the image builds and its a simple package install
> feat: added ca-certificates so docker can connect within tailscale

- op-monitorism/faultproof_withdrawals/state.go
This pull request includes changes to the `op-monitorism/faultproof_withdrawals/state.go` file to introduce a new gauge metric for monitoring the service status. The most important changes include the addition of the `UpGauge` metric and its integration into the existing metrics structure and methods.
Introduction of `UpGauge` metric:
* [`op-monitorism/faultproof_withdrawals/state.go`](diffhunk://#diff-c5799769a4a261d24d0525cbca1b63a12df911f2fcbb2068c2b3e2b69e74547bR179): Added `UpGauge` to the `Metrics` struct to monitor if the service is up and running.
* [`op-monitorism/faultproof_withdrawals/state.go`](diffhunk://#diff-c5799769a4a261d24d0525cbca1b63a12df911f2fcbb2068c2b3e2b69e74547bR279-R283): Initialized `UpGauge` in the `NewMetrics` function and set its value to 1 to …
> feat: Add 'up' gauge metric to track service status for faultproof_withdrawals

- op-monitorism/Makefile
- op-monitorism/faultproof_withdrawals/.env.op.mainnet.example
- op-monitorism/faultproof_withdrawals/.env.op.sepolia.example
- op-monitorism/faultproof_withdrawals/monitor.go
- op-monitorism/faultproof_withdrawals/state_test.go
- op-monitorism/faultproof_withdrawals/validator/l2_proxy.go
- op-monitorism/faultproof_withdrawals/validator/optimism_portal2_helper.go
- op-monitorism/faultproof_withdrawals/validator/proven_withdrawal_validator.go
This pull request introduces several enhancements and fixes to the `op-monitorism` project, focusing on improving test execution flexibility, refining configurations, optimizing binary search logic, and adding robustness to client handling in the withdrawal monitoring system. Additionally, new unit tests are introduced for better coverage of state-related functionality.
* Modified the `test` target to allow running tests for specific modules by passing arguments. This improves flexibility in testing workflows. (`op-monitorism/Makefile`, [op-monitorism/MakefileL45-R53](diffhunk://#diff-23a081236d4827b9c7f4df7fa1bd5c13a925f75ba83a1c69a441b07120ae8333L45-R53))
* Updated the `help` target to reflect the new capability of the `test` target, providing clearer instructions for …
> Fix issues
